dist: bionic
language: cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install libssl-dev qtbase5-dev cmake make g++-9 libqt5sql5-mysql mysql-server
  - sudo systemctl start mysql
  - cat balancedbanana.sql | sudo mysql
  - echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'banana';"$'\n'"ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';"$'\n'"FLUSH PRIVILEGES;" | sudo mysql

script:
  - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake -DCOVERAGE=1 .
  - cmake --build .
  - "ctest --verbose . || :"

after_success:
  - coveralls --root . --gcov gcov-9 -E ".*testsrc.*" -E ".*contrib.*" -E ".*google.*" -E ".*gtest.*" -E ".*Webserver.*" -E ".*Net.*" -E ".*CMakeFiles.*"