dist: bionic
language: cpp

addons:
  apt:
    packages:
      - g++-9

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get update
  - sudo apt-get -y install libssl-dev qtbase5-dev cmake make

script:
  - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake -DCOVERAGE=1 .
  - cmake --build .
  - "ctest --verbose . || :"

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*Webserver.*" -E ".*Net.*" -E ".*CMakeFiles.*"