dist: bionic
language: cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install libssl-dev qtbase5-dev cmake make g++-9 libqt5sql5-mysql mysql-server 

script:
  - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake -DCOVERAGE=1 .
  - cmake --build .
  - "ctest --verbose . || :"

after_success:
  - coveralls --root . --gcov gcov-9 -E ".*contrib.*" -E ".*google.*" -E ".*gtest.*" -E ".*Webserver.*" -E ".*Net.*" -E ".*CMakeFiles.*"